import logging


"""
Partly Generated by chatgpt

"""

def setup_logger(
        name="app_logger",
        level=logging.INFO,
):
    # Create logger
    logger = logging.getLogger(name)
    logger.setLevel(level)
    logger.propagate = False  # Avoid duplicate logs

    # Formatter
    formatter = logging.Formatter(
        fmt="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )

    # Console handler (with colors if available)
    try:
        from colorama import Fore, Style, init
        init(autoreset=True)

        class ColorFormatter(logging.Formatter):
            COLORS = {
                logging.DEBUG: Fore.CYAN,
                logging.INFO: Fore.GREEN,
                logging.WARNING: Fore.YELLOW,
                logging.ERROR: Fore.RED,
                logging.CRITICAL: Fore.MAGENTA + Style.BRIGHT,
            }

            def format(self, record):
                color = self.COLORS.get(record.levelno, "")
                message = super().format(record)
                return f"{color}{message}{Style.RESET_ALL}"

        console_handler = logging.StreamHandler()
        console_handler.setFormatter(ColorFormatter(formatter._fmt, formatter.datefmt))
    except ImportError:
        console_handler = logging.StreamHandler()
        console_handler.setFormatter(formatter)

    # Add handlers if not already added
    if not logger.handlers:
        logger.addHandler(console_handler)

    return logger



log = setup_logger()
