
"""
Partly Generated by chatgpt

"""

from pathlib import Path

import numpy as np
import torch
from segment_anything import sam_model_registry, SamPredictor

from .paths import PROJECT_ROOT


SAM_MODEL_TYPE = "vit_b"
SAM_CHECKPOINT = PROJECT_ROOT / "models" / "sam" / "sam_vit_b.pth"

_DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
_SAM_PREDICTOR = None

i=0
def get_sam_predictor() -> SamPredictor:
    global _SAM_PREDICTOR
    if _SAM_PREDICTOR is None:
        sam = sam_model_registry[SAM_MODEL_TYPE](checkpoint=str(SAM_CHECKPOINT))
        sam.to(device=_DEVICE)
        _SAM_PREDICTOR = SamPredictor(sam)
    return _SAM_PREDICTOR


def sam_segment_from_anomaly(
    img_np: np.ndarray,
    anomaly_grid: np.ndarray,
    num_points: int = 5,
) -> np.ndarray:
    
    predictor = get_sam_predictor()
    predictor.set_image(img_np)

    H_img, W_img = img_np.shape[:2]
    H_p, W_p = anomaly_grid.shape

    flat = anomaly_grid.ravel()
    num_points = min(num_points, flat.size)
    top_idx = np.argpartition(flat, -num_points)[-num_points:]
    patch_coords = np.column_stack(np.unravel_index(top_idx, (H_p, W_p)))  

    patch_h = H_img / H_p
    patch_w = W_img / W_p
    points = []
    for (pi, pj) in patch_coords:
        cy = (pi + 0.5) * patch_h
        cx = (pj + 0.5) * patch_w
        points.append([cx, cy])  

    points = np.array(points, dtype=np.float32)
    labels = np.ones(points.shape[0], dtype=np.int32) 

    masks, scores, _ = predictor.predict(
        point_coords=points,
        point_labels=labels,
        multimask_output=False,
    )

    sam_mask = masks[0].astype(np.uint8)  
    return sam_mask
